import { Poppins } from "next/font/google";
import "./globals.css";
import Header from '@/app/components/Header'

const poppins = Poppins({ subsets: ["latin"], weight:['100', '200', '400', '800'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />

        {children}
      </body>
    </html>
  );
}
